// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB10GYbka5J9DAdS9ijwoERycBv5EQjPmI',
    appId: '1:152746090057:web:79a6ebec2d7eccd18ae998',
    messagingSenderId: '152746090057',
    projectId: 'image-uploader-a86a6',
    authDomain: 'image-uploader-a86a6.firebaseapp.com',
    storageBucket: 'image-uploader-a86a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXNG-g8xsz7IkxZUv64nJ0IkfaZUySFgM',
    appId: '1:152746090057:android:7c0740da3384b6628ae998',
    messagingSenderId: '152746090057',
    projectId: 'image-uploader-a86a6',
    storageBucket: 'image-uploader-a86a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFWoZRVFFw7K7TZzNDIpVqxccF-enclVE',
    appId: '1:152746090057:ios:4548a27148a48af88ae998',
    messagingSenderId: '152746090057',
    projectId: 'image-uploader-a86a6',
    storageBucket: 'image-uploader-a86a6.appspot.com',
    iosClientId: '152746090057-4j1hi79msuk4j813e6pebcghhg5m464q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFWoZRVFFw7K7TZzNDIpVqxccF-enclVE',
    appId: '1:152746090057:ios:4548a27148a48af88ae998',
    messagingSenderId: '152746090057',
    projectId: 'image-uploader-a86a6',
    storageBucket: 'image-uploader-a86a6.appspot.com',
    iosClientId: '152746090057-4j1hi79msuk4j813e6pebcghhg5m464q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudy',
  );
}
